AWSTemplateFormatVersion: "2010-09-09"
Description: "Database and EFS"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Global Parameters"
        Parameters:
          - VPCStackID

Parameters:
  VPCStackID:
    Type: String
    Description: "VPC-Stack-ID"
    Default: "FLOW-WP-VPC"


Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: Wordpress-demo
      PerformanceMode: generalPurpose
      ThroughputMode: bursting

  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: FileSystem Security Group
      VpcId: 
        Fn::ImportValue: !Sub "${VPCStackID}-VPC"
      GroupName: Wordpress-Demo-EFS-SG
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: 2049
        ToPort: 2049
        CidrIp: 10.0.0.0/16

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId:
        Fn::ImportValue: !Sub "${VPCStackID}-SubnetPrivate1"
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId:
        Fn::ImportValue: !Sub "${VPCStackID}-SubnetPrivate2"
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref FileSystem
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: "/bitnami"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: wp-db-subnet-group
      DBSubnetGroupDescription: wp-db-subnet-group
      SubnetIds:
      - Fn::ImportValue: !Sub "${VPCStackID}-SubnetPublic1"
      - Fn::ImportValue: !Sub "${VPCStackID}-SubnetPublic2"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      VpcId:
        Fn::ImportValue: !Sub "${VPCStackID}-VPC"
      GroupName: Wordpress-Demo-RDS-SG
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.0.0.0/16

  WordpressDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: wp-db1
      DBInstanceClass: db.t3.micro
      DBName: wordpress
      Engine: mysql
      MasterUserPassword: supersecretpassword
      MasterUsername: admin
      PubliclyAccessible: false
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup

Outputs:
  EFSFSId:
    Description: "ID of EFS FS"
    Value:
      Ref: "FileSystem"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "FileSystem"]]

  RDSEndpointAddress:
    Description: "RDS Endpoint Address"
    Value: !GetAtt WordpressDB.Endpoint.Address
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "WordpressDB"]]

  EFSAccessPoint:
    Description: "EFS Access Point ID"
    Value: !GetAtt AccessPoint.AccessPointId
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "AccessPoint"]]